### ISSUE TITLE
Falta el request de token

### ISSUE THREAD

**Issue by ytselabo** [decidir/sdk-php-v2#1]
Buenas tardes!

Estoy comenzando con la implementación de la api rest, y estoy viendo que faltan los datos en el readme para el request del token. mismo en el ejemplo completo, está este comentario //falta seccion get token de pago.

Me podrían ayudar con esto?

gracias!

**Comment by drarko** [comment]
Estimado, se actualizo la documentación agregando los pasos necesarios para obtener el token de pago mediante las SDK de Frontend.
Cualquier consulta, reabrir.
Saludos
