### ISSUE TITLE
Error en Decidir/lib/Payment/Data.php con campo user_id

### ISSUE THREAD

**Issue by mauromm** [decidir/sdk-php-v2#10]
En el commit :

https://github.com/decidir/sdk-php-v2/commit/16278abd8cf87fa5eaaafb954f7236caa5b34b1a#diff-93d44d3cc71eea03e62001b5c59bf941

Se elimino el campo user_id del constructor de la clase Decidir\Payment\Data, en donde llama a   $this->setRequiredFields(...). Esto hace que cuando utilizo el metodo de **/payments** y envio este campo, que es requerido en la documentacion oficial, el sdk me devuelta una excepcion y no me deja continuar las compras "Campo: user_id no existe.".

Esto no pasaba en la version anterior del sdk, y es algo que lo tenemos implementado en un ambiente productivo funcionando. Por favor revisar esto.  

Gracias

**Comment by leonelvsc** [comment]
Falta documentacion en realidad, pero si miras bien aca
https://decidirv2.api-docs.io/1.0/tokenizacion-de-tarjetas/ejecucion-del-primer-pago

Dicen que el formato es de la siguiente forma
[
    'customer' => ['id' => '123']
]

Suerte!

**Comment by mauromm** [comment]
No, lo que ves ahí es como se usa posteando directamente la info. El sdk esta hecho como una herramienta que facilita el uso de eso, y nos abstrae un poco para que lo podamos enviar de otra forma con php. Esta implementacion la vengo trabajando desde los primeros dias que lanzaron esto, y en ese comit lo rompieron.

saludos!

**Comment by leonelvsc** [comment]
Te digo porque me pasó lo mismo que a vos en vez de mandar 'customer_id' lo mandé como en la respuesta anterior y me funciona bien.

Pero es verdad lo que decis, deberia abstraernos la SDK , no es el caso

**Comment by mmansilla-prisma** [comment]
Buenos días, hoy en día se encuentran como campos opcionales.

Saludos!
