### ISSUE TITLE
Fallo de metodo PUT al realizar una captura

### ISSUE THREAD

**Issue by joaquin-becerra** [decidir/sdk-php-v2#12]
- El metodo RESTClient::put() no tiene los parametros $action y $data 
https://github.com/decidir/sdk-php-v2/blob/master/Decidir/lib/RESTClient.php#L57

- El metodo PUT falla al realizar una captura, devuelve el error:

 {"error_type":"malformed_request_error","message":"Invalid Json","code":"Malformed request error"}

El problema es el parametro curl CURLOPT_PUT que se agrega en:
 
 https://github.com/decidir/sdk-php-v2/blob/master/Decidir/lib/RESTClient.php#L92

Hay que comentarlo para que funcione (@see https://decidir.api-docs.io/1.0/transacciones-en-dos-pasos/GHnbdRF7RjKkiX7Fv ver el codigo generado para php)

 Saludos

**Comment by grago** [comment]
Hola, estoy obteniendo un error al intentar capturar el pago. Ejemplo:

`        $keys_data = array('public_key' => 'e9cdb99fff374b5f91da4480c8dca741',
           'private_key' => '92b71cf711ca41f78362a7134f87ff65');

        $ambient = "test";//valores posibles: "test" , "prod" o "qa"
        $connector = new \Decidir\Connector($keys_data, $ambient);  


         $data = array(
          "amount" => 500,
        );

    try {
        $response = $connector->payment()->CapturePayment("12954386", $data);
        dump($response);

            die();
    } catch( \Exception $e ) {
        dump($e->getData());
        die();
    }           
`

El error devuelto es:

`{"error_type":"invalid_request_error","validation_errors":[{"code":"State error","param":"approved"}]}`

Cuál podría ser el error? Muchas gracias.

**Comment by nunco** [comment]
@grago buenos días.
para realizar captura, tenes que utilizar sites_id con la funcionalidad habilitada.
Entonces los pagos quedan pre-approve, para que luego hagas el approved (PUT). 
Proba con esto y comentame como te fue
publicKey: 41cbc74acc604a109157bb8394561d27
privateKey: 1fb6dc55c0a1489db411a8ee8f9c9707

saludos.-
