### ISSUE TITLE
Error en devolución parcial de transaccion distribuida

### ISSUE THREAD

**Issue by VadinoMatias** [decidir/sdk-php-v2#13]
Estimados, intentamos realizar una devolución de pago distribuido pero empezamos a tener varios errores por parte del modulo.

Encontramos que el problema esta en la función partialRefund($data, $operationId) del archivo \vendor\decidir2\php-sdk\Decidir\lib\Payment.php

Pudimos ver que hardcodeando la función con un ejemplo pudimos hacer que la devolución parcial funcione correctamente.

`public function partialRefund($data, $operationId){
		if(empty($operationId)){
			throw new \Exception("Empty Operation id");
		}
                $RESTResponse = $this->serviceREST->post("payments/".$operationId."/refunds", 
                        '{
                            "sub_payments": [
						{"id":2431,"amount":200}
					]
	
                        }'
                );
                
		$ArrayResponse = $this->toArray($RESTResponse);

		return new \Decidir\PartialRefund\PaymentPartialRefund($ArrayResponse);
	}`

¿tienen pensado realizar una corrección de este error en una versión nueva en breve?

**Comment by VadMat** [comment]
Por las dudas lo agregamos, llegamos a agregar este código hardcodeado por lo propuesto en la guía

https://decidir.api-docs.io/1.0/transacciones-distribuidas/5drbqSWhCHDXPLp8h

**Comment by mmansilla-prisma** [comment]
Buenos días, esto ya se encuentra agregado 
![image](https://user-images.githubusercontent.com/83774187/149171870-08b39e1b-f5e1-43a3-ad5c-0465e7345aed.png)

Saludos!
