### ISSUE TITLE
Error escribiendo log en RESTClient.php no deja finalizar compras

### ISSUE THREAD

**Issue by mauromm** [decidir/sdk-php-v2#15]
Hola, hay un error grave en Decidir/lib/RESTClient.php linea 100. Se esta intentando loguear un error en apache siempre que se intenta ejecutar un pago:

error_log(print_r($header_http,true),3,"/var/log/apache2/error_log.log");

Lo grave no es que solamente se loguea en apache, sino que **lo hace en un directorio hardcodeado**, y no puede funcionar con la mayoria de los servidores (centos por ejemplo) o que utilicen un virtualhost diferente con otra ubicación de los logs de apache. 

Para que funcione correctamente tuve que comentar esta linea.

Gracias

**Comment by joaquin-becerra** [comment]
Una posible solucion seria que la clase tenga algunos atributos estaticos:

 lastError
 lastRequest
 lastResponse

Y que ante una falla pueda accederse a esa info

**Comment by mmansilla-prisma** [comment]
Buenas tardes, les confirmo que ya se elimino la linea menciona.

Saludos!
