### ISSUE TITLE
URL para imprimir ticket en pagos offline

### ISSUE THREAD

**Issue by connaxisltatarin** [decidir/sdk-php-v2#16]
Hola buenas, estuve realizando algunas pruebas de ejecución de pagos tipo offline en test y no veo en la respuesta la información para mostrarle al usuario el cupón para imprimir. Como se realiza esto?

**Comment by mmansilla-prisma** [comment]
Buenos días @connaxisltatarin , 

No existe una url del cupón, en la respuesta se entrega el bardcode
![image](https://user-images.githubusercontent.com/83774187/149170631-49a47397-d35a-479b-b14b-d8daaddcd61a.png)

Saludos!
