### ISSUE TITLE
Error al mandar a autorizar pago

### ISSUE THREAD

**Issue by cmarassi** [decidir/sdk-php-v2#17]
Buenas !! 

Me esta dando este error al querer autorizar un pago, ya genere el token => Error Respuest payment<br>string(14) "origin_site_id"

el array de datos que envio es :

	try {
		$response = $connector->payment()->ExecutePayment($data);
		echo("Respuest payment<br>");
		print_r($response);
		
		echo("<br><br>");
		echo("Status: ".$response->getStatus()."<br><br>");

		echo("Status detail<br>");
		
		echo("site tranaction:".$response->getSiteTransactionId()."<br>");
		echo("Ticket:".$response->getStatus_details()->ticket."<br>");
		echo("Card Authorization Code: ".$response->getStatus_details()->card_authorization_code."<br>");
		echo("Address Validation Code : ".$response->getStatus_details()->address_validation_code."<br>");
		var_dump($response->getStatus_details()->error);//echo(print_r($response->getStatus_details()->error,true));	
		

	} catch(\Exception $e) {
		echo("<br>Error Respuest payment<br>");
		var_dump($e->getData());
	}

No encontre en la documentación nada y de soporte no me responden

**Comment by ConradGalli** [comment]
Tenes mal el origin_site_id

**Comment by cmarassi** [comment]
> 
> 
> Tenes mal el origin_site_id

Y desde donde obtengo el  **origin_site_id**

**Comment by sevav** [comment]
Tarde, pero espero ayude.

Este error sucede cuando las apikey no son las correctas.
Corroborar que en modo development, se están enviando las apikey:

`DECIDIR_PUBLIC_KEY_TEST=e9cdb99fff374b5f91da4480c8dca741
DECIDIR_PRIVATE_KEY_TEST=92b71cf711ca41f78362a7134f87ff65`

Como indica los manuales. 
Desde soporte me indicaron otras que no funcionan.

**Comment by mmansilla-prisma** [comment]
Buenas tardes, mil disculpas por la tardanza al responder

Hay un error en el connector, estas enviando apikeys que no están habilitadas.
Cierro el issue por la antigüedad del mismo, si seguís con el problema lo abrimos nuevamente y te ayudamos.

Saludos

**Comment by ConradGalli** [comment]
> Cierro el issue por la antigüedad del mismo, si seguís con el problema lo abrimos nuevamente y te ayudamos.

Buen dia, estamos con el mismo problema.

Me devuelve esto la api

Status: rejected
Status detail
site tranaction:92002191
Ticket:4
Card Authorization Code:
Address Validation Code : VTE0000

**Comment by Nanod10** [comment]
Buen dia!
Por acá también nos devuelve un error al utilizar las ApiKeys de TESTING brindadas por DECIDIR via email luego de crear una cuenta D+ ("Decidir Plus")

Obtengo el token desde el SDK de JavaScript durante el proceso de checkout, al confirmar la compra envió el token al backend y realizo la ejecución del pago a través del SDK de PHP v1.5.6

Datos que envió para la ejecución del pago:

```
{
    "site_transaction_id": "28303-e871a2e88288a9ba168b00fcbcf94",
    "token": "028f27d7-3a1f-4679-88ae-788ecd12ad3f",
    "customer": {
        "id": "110380", // el id del usuario en mi sitio web
        "email": "el_email_del_usuario@gmail.com",
        "ip_address": "xxx.xxx.xxx.xxx" // la ip del usuario
    },
    "payment_method_id": 1,
    "bin": "450799",
    "amount": 25.39,
    "currency": "ARS",
    "installments": 1,
    "description": "",
    "payment_type": "single",
    "sub_payments": []
}
```

Devuelve: 

```
{
"error_type": "invalid_request_error",
  "validation_errors": [ {
      "code": "invalid_site",
      "param": "datos_site.origin_site_id"
  } ]
}
```

Incluso si agrego al request de ejecucion del pago alguno o todos los siguientes parametros falla con el mismo mensaje de error:

```
"establishment_name": "NOMBRE DE MI EMPRESA",
"site_id": "92009999",   // site_id provisto por el email de datos de testing luego del registro en D+
"origin_site_id": "92009999",
```
Como nota adicional, en "site_transaction_id" estoy enviando el id del pedido en mi plataforma, concatenando un hash generado a partir del timestamp actual, segun la documentacion no deberia haber problemas:

> Campo | Descripcion | Oblig | Restricciones | Ejemplo
> site_transaction_id | nro de operacion | SI | Alfanumerico de hasta 39 caracteres | "prueba 1"

@mmansilla-prisma mencionaste que las api keys de testing no estan habilitadas, 

Me he comunicado por el chat de la plataforma D+, por telefono y via e-mail hace 5 dias que tengo este error y no puedo continuar con la implementación.

Le agradecería si podría guiarme en como resolver este problema.

Saludos!

**Comment by mmansilla-prisma** [comment]
> > Cierro el issue por la antigüedad del mismo, si seguís con el problema lo abrimos nuevamente y te ayudamos.
> 
> Buen dia, estamos con el mismo problema.
> 
> Me devuelve esto la api
> 
> Status: rejected Status detail site tranaction:92002191 Ticket:4 Card Authorization Code: Address Validation Code : VTE0000

Buenos dias, 
tenes el body con el cual te dio este error ? y a que ambiente le estas pegando ? 
Saludos

**Comment by ConradGalli** [comment]
> > > Cierro el issue por la antigüedad del mismo, si seguís con el problema lo abrimos nuevamente y te ayudamos.
> > 
> > 
> > Buen dia, estamos con el mismo problema.
> > Me devuelve esto la api
> > Status: rejected Status detail site tranaction:92002191 Ticket:4 Card Authorization Code: Address Validation Code : VTE0000
> 
> Buenos dias, tenes el body con el cual te dio este error ? y a que ambiente le estas pegando ? Saludos

Es a produccion, estan entregando API KEYS de produccion para decidir + no aptas para CYBERSOURCE, quedan todas en negro..

**Comment by Nanod10** [comment]
Hola Marcelo @mmansilla-prisma, muchas gracias por responder!

**Sobre las ApiKeys que utilizo:**
Si, efectivamente hay una diferencia. Las Api keys que utilizo fueron brindadas vía email (automatico) luego de dar de alta la cuenta "D+". 
Nos llegaron 2 emails, uno con las keys de pruebas y datos de tarjetas de pruebas (para el ambiente "test") y otro con los datos para "Producción". 
Directamente Interprete que esas son "mis keys de prueba" y que están ligadas a mi usuario cuando accedo a [developers.decidir.com.ar](http://decidir.com.ar/desarrolladores/home) > sección "desarrolladores" > "acceso al portal de sandbox"
Imaginaba que si usaba las keys que brindaron por email iba a poder ver reflejado en el portal de sandbox las pruebas de las transacciones, efectuar devoluciones, etc. **pero al utilizarlas me da ese error que mencione ("invalid_site datos_site.origin_site_id").** y no puedo ejecutar los pagos.

Ya había probado antes del registro utilizar las keys de pruebas que me brindas en tu respuesta (que son las que figuran en la documentación) y los datos de tarjetas de pruebas que usan en los ejemplos de la documentación y en ese caso **todo funciona correctamente pero no se refleja en mi portal de sandbox**

**Hay forma de utilizar/habilitar las apikeys de pruebas propias?** y ver reflejado en el portal sandbox las transacciones de prueba realizadas o eso no esta funcionando aun?

Saludos!!

**Comment by mmansilla-prisma** [comment]
> Hola Marcelo @mmansilla-prisma, muchas gracias por responder!
> 
> **Sobre las ApiKeys que utilizo:** Si, efectivamente hay una diferencia. Las Api keys que utilizo fueron brindadas vía email (automatico) luego de dar de alta la cuenta "D+". Nos llegaron 2 emails, uno con las keys de pruebas y datos de tarjetas de pruebas (para el ambiente "test") y otro con los datos para "Producción". Directamente Interprete que esas son "mis keys de prueba" y que están ligadas a mi usuario cuando accedo a [developers.decidir.com.ar](http://decidir.com.ar/desarrolladores/home) > sección "desarrolladores" > "acceso al portal de sandbox" Imaginaba que si usaba las keys que brindaron por email iba a poder ver reflejado en el portal de sandbox las pruebas de las transacciones, efectuar devoluciones, etc. **pero al utilizarlas me da ese error que mencione ("invalid_site datos_site.origin_site_id").** y no puedo ejecutar los pagos.
> 
> Ya había probado antes del registro utilizar las keys de pruebas que me brindas en tu respuesta (que son las que figuran en la documentación) y los datos de tarjetas de pruebas que usan en los ejemplos de la documentación y en ese caso **todo funciona correctamente pero no se refleja en mi portal de sandbox**
> 
> **Hay forma de utilizar/habilitar las apikeys de pruebas propias?** y ver reflejado en el portal sandbox las transacciones de prueba realizadas o eso no esta funcionando aun?
> 
> Saludos!!

Te entiendo, podrías enviarme el site_id y las apikey que te llegaron, asi puedo verificar que sean las correctas y que esten activas para poder transaccionar en el ambiente de test, te dejo mi mail mmansilla@prismamp.com

Aguardo tu contacto por mail, saludos!

**Comment by bigsdp** [comment]
buenas como estan, yo no puedo avanzar. quiero generar el hash para levantar el formulario de pago , y me dice siempre 
Error: Property hash not exists

hay algun codigo de prueba en modo test, q reemplazando los api key funcione?

**Comment by nunco1** [comment]
@bigsdp buenas tardes. Tenes que utilizar las credenciales de pruebas que te llegan con el alta + templateId. te dejo uno de test para que valides. este es sin cybersource.
curl --location 'https://developers.decidir.com/web/forms' \
--header 'Content-Type: application/json' \
--header 'apikey: 9e3b3e87d7d64b88815c59e4f12fe146' \
--header 'Cookie: TS017a11a6=012e46d8ee927e9236dd07fb17eb87cd5fab413dc3f931ed2953c61294ae448ff8b8ecec9314ec90b20126cc0a77c36d642293bd79' \
--data-raw '{
    "site": {
        "transaction_id": "1719354115",
        "template": {
            "id": 10
        }
    },
    "public_apikey": "78460533452d491fb71ea9883e37665e",
    "establishment_name": "establishment_name",
    "customer": {
        "id": "1060129",
        "email": "jhon@hotmail.com",
        "ip_address": "186.38.99.124",
        "identification": {
            "type": "dni",
            "number": "17095506"
        }
    },
    "payment": {
        "amount": 2000,
        "currency": "ARS",
        "installments": 1,
        "payment_type": "single",
        "sub_payments": []
    },
     "redirect_url": "https://google.com.ar",
    
    "cancel_url": "https://successurl.free.beeceptor.com"
}'
