### ISSUE TITLE
not found error

### ISSUE THREAD

**Issue by arieldupuy90** [decidir/sdk-php-v2#24]
se obtiene el siguiente error al ejecutar $conector->payment()->PaymentList();

#0 /home/adupuy/proyectos/GatewayDigital/vendor/decidir2/php-sdk/Decidir/lib/PaymentsList/PaymentsListResponse.php(13): Decidir\Data\Response->__construct()
#1 /home/adupuy/proyectos/GatewayDigital/vendor/decidir2/php-sdk/Decidir/lib/Payment.php(82): Decidir\PaymentsList\PaymentsListResponse->__construct()
#2 /home/adupuy/proyectos/GatewayDigital/core/classes/decidir.php(435): Decidir\Payment->PaymentList()

**Comment by arieldupuy90** [comment]
en la version V1.5.0 no ocurre dicho error

**Comment by mmansilla-prisma** [comment]
Buenas tardes @arieldupuy90, 

Te esta fallando porque hace falta enviarle un parámetro a PaymentList, te dejo la documentación 
![image](https://user-images.githubusercontent.com/83774187/149013936-c0f4f493-6a49-411b-a0b3-bf81a888b05a.png)
https://github.com/decidir/sdk-php-v2#getallpayments

Saludos!
