### ISSUE TITLE
Response /payments --> status:"rejected" - test sdk-php

### ISSUE THREAD

**Issue by Stefano-Mazziotta** [decidir/sdk-php-v2#25]
Buenos días. Les cuento mi problema al testear la sdk-php.
Mi objetivo es obtener una response del /payments con estado válido pero no lo consigo.
Desde el sdk-js, obtengo correctamente el token SIN ACTIVAR el fraud_detection.

En el back. Mi data para el request es el siguiente:

$data = array(
	"site_transaction_id" => "123654798",
	"token" => "28c1c5a0-cf7d-496a-b733-2d2ab908241e",
	"customer" => array(
					  "id" => "1", 
					  "email" => "test_user_19653727@testuser.com",
					  "ip_address" => "192.168.100.2"
					  ),
	"payment_method_id" => 1,
	"bin" => "450799",
	"amount" => 558.0,
	"currency" => "ARS",
	"installments" => 1,
	"description" => "venta",
	"payment_type" => "single",
	"sub_payments" => array(),
  );

Al hacer la solicitud con $data obtengo respuesta de la api de /payments pero esa respuesta tiene status: "rejected":

{"id":12198192,"site_transaction_id":"1","payment_method_id":1,"card_brand":"Visa","amount":100,"currency":"ars","status":"rejected","status_details":{"ticket":null,"card_authorization_code":"","address_validation_code":null,"error":{"type":"cybersource_error","reason":{"id":-1,"description":""}}},"date":"2021-11-29T17:02Z","customer":{"email":"test_user_19653727@testuser.com"},"bin":"450799","installments":1,"first_installment_expiration_date":null,"payment_type":"single","sub_payments":[],"sit**e_id":"92002092","fraud_detection":{"status":{"decision":"black","request_id":null,"reason_code":-1,"description":"validation","review":null,"details":{"error_type":"invalid_request_error","validation_errors":[{"code":"missing","param":"fraud_detection"}]}}}**,"aggregate_data":null,"establishment_name":"92002092","spv":null,"confirmed":null,"pan":null,"customer_token":null,"card_data":"/tokens/12198192","token":"75a42b02-8b21-42a0-a263-135b77f510fb"}

Destaco información de la respuesta anterior:
 **type:"cybersource_error", decision:"black", code:"missing", param:"fraud_detection".**

Por otro lado, si en el sdk-js obtengo el token con fraud_detection activado sucede lo siguiente.
En el back mantengo la misma data para el request y la response de Decidir es la siguiente:

{"id":12198198,"site_transaction_id":"1","payment_method_id":1,"card_brand":"Visa","amount":100,"currency":"ars","status":"rejected","status_details":{"ticket":null,"card_authorization_code":"","address_validation_code":null,"error":{"type":"cybersource_error","reason":{"id":-1,"description":""}}},"date":"2021-11-29T17:06Z","customer":{"email":"test_user_19653727@testuser.com"},"bin":"450799","installments":1,"first_installment_expiration_date":null,"payment_type":"single","sub_payments":[],"site_id":"92002092","fraud_detection":{"status":{"decision":"black","request_id":null,"reason_code":-1,"description":"validation","review":null,"details":{"error_type":"invalid_request_error","validation_errors":[{"code":"missing","param":"bill_to"}]}}},"aggregate_data":null,"establishment_name":"92002092","spv":null,"confirmed":null,"pan":null,"customer_token":null,"card_data":"/tokens/12198198","token":"a3f0a308-3787-4cce-baa9-c9001d29b296"}

Destaco información de la respuesta anterior:
 **type:"cybersource_error", decision:"black", code:"missing", param:"bill_to".**
 
 
 Entiendo que error tipo "black" es falta de información, pero en mi caso, no quiero activar el fraud_detection ya que estoy en un entorno de prueba para validar la ejecución de pago. Hay alguna forma de desactivar cyberSource para que no me lo requiera en el request?
 
 Seguí los pasos de la documentación, pero surge estas trabas.
 Me interesa verificar si el servicio funciona antes de integrarlo al sitio web.
 
 Espero que me puedan ayudar, muchas gracias!!

**Comment by ConradGalli** [comment]
Las credenciales que estas usando no son validas, por eso te devuelve ese error, proba con credenciales de testeo o volve a solicitar las de produccion

**Comment by Stefano-Mazziotta** [comment]
Muchas gracias por tu respuesta. Yo estoy utilizando las api key pública y privada que me pasó Decidir. De momento quería probar en el entorno de test que brinda Decidir, no sería correcto utilizar las credenciales que ellos me pasaron? Nuevamente, gracias. Saludos!

**Comment by Stefano-Mazziotta** [comment]
Efectivamente, eran las Credenciales. Muchas gracias! igualmente las que estaba utilizando eran key de test que brindó Decidir al cliente. Con esto último me surge una duda, al dar de alta las credenciales tiene un tiempo de espera para utilizarlas o es instantáneo? Nuevamente, gracias por tu respuesta. Saludos!!

**Comment by ConradGalli** [comment]
> e, eran las Credenciales. Muchas gracias! igualmente las que estaba utilizando eran key de test que brindó Decidir al cliente. Con esto último me surge una duda, al dar de alta las credenciales tiene un tiempo de espera para utilizarlas o es instantáneo? Nuevamente, gracias por tu respuesta. Saludos!!

Es instantaneo pero estas ultimas dos semanas no las estan activando.

**Comment by Stefano-Mazziotta** [comment]
Excelente información, gracias y buena semana!

**Comment by JorgeEnDH** [comment]
Estimados, tengo el mismo error que Stefano **(type:"cybersource_error", decision:"black", code:"missing", param:"bill_to"**.), donde solicitaron las ApiKeys ????... Gracias.

**Comment by Stefano-Mazziotta** [comment]
Buen día Jorge! En mi caso, utilicé las API key de prueba que te ofrece la documentación de Decidir:
https://decidirv2.api-docs.io/1.0/transacciones-simples/flujo-de-una-transaccion-simple

Aclaro, las API keys de la documentación son para el entorno de test. 
Cuando se integra al entorno productivo tienen que ser las credenciales válidas las cuáles te ofrece el personal de Decidir.
