### ISSUE TITLE
sdk en packagist?

### ISSUE THREAD

**Issue by mauromm** [decidir/sdk-php-v2#4]
Hola, cuando podrán subir el sdk al packagist para que se pueda instalar de la misma forma que el de la versión anterior mediante composer?

Saludos

**Comment by nicolasdanelon** [comment]
@mauromm está acá https://packagist.org/packages/decidir2/php-sdk
btw, yo no soy de decidir o prisma, eh. sólo encontré eso y ví tu issue

**Comment by mauromm** [comment]
Buenísimo, gracias @nicolasdanelon ! No lo había visto, o lo acaban de agregar.
