### ISSUE TITLE
PaymentResponse - Metodo para obtener todos los atributos de la respuesta

### ISSUE THREAD

**Issue by joaquin-becerra** [decidir/sdk-php-v2#6]
Estimados

 Veo que no hay un método que permita obtener la respuesta completa de una operacion de pago, por ejemplo:

`
$response = $connector->payment()->ExecutePayment($data);
$response->getData(); // esto genera una excepcion
`
Seria bueno algo similar para obtener todos los atributos de la respuesta de una sola vez, y no tener que ejecutar el get por cada atributo que 'suponemos' estan en la respuesta, ademas si preguntamos por un parámetro equivocado (ej getNn()) se dispara una excepcion cortando el flujo de nuestro script.

Hay algun workarround para esto?

Saludos y Gracias

**Comment by drarko** [comment]
Estimado, 
Solucionado en los ulitmos release.
Saludos
